import type { GameCategory } from "@/types";

export const GAME_CATEGORIES: GameCategory[] = [
  {
    gameSlug: "lien-quan",
    gameName: "LIÊN QUÂN MOBILE",
    gameIcon: "🎮",
    categories: [
      {
        id: "lq-trang",
        name: "Nick Thông Tin Đẹp",
        slug: "nick-thong-tin-dep",
        typeValue: "trang",
        image: "../../public/nakvt.gif",
        priceFrom: 100000,
        stock: 8,
      },
      {
        id: "lq-reg",
        name: "Nick Reg Trắng",
        slug: "nick-reg-trang",
        typeValue: "reg",
        image: "/img/lq-reg.jpg",
        priceFrom: 30000,
        stock: 110,
      },
      {
        id: "lq-rlp",
        name: "Nick RLP",
        slug: "nick-rlp",
        typeValue: "rlp",
        image: "/img/lq-rlp.jpg",
        priceFrom: 270000,
        stock: 6,
      },
    ],
  },
  {
    gameSlug: "valorant",
    gameName: "VALORANT",
    gameIcon: "🔫",
    categories: [
      {
        id: "val-rank",
        name: "Acc Rank Cứng",
        slug: "acc-rank-cung",
        typeValue: "rank",
        image: "/img/val-rank.jpg",
        priceFrom: 150000,
        stock: 15,
      },
      {
        id: "val-skin",
        name: "Acc Full Skin",
        slug: "acc-full-skin",
        typeValue: "skin",
        image: "/img/val-skin.jpg",
        priceFrom: 500000,
        stock: 4,
      },
    ],
  },
  {
    gameSlug: "free-fire",
    gameName: "FREE FIRE",
    gameIcon: "🔥",
    categories: [
      {
        id: "ff-vip",
        name: "Acc VIP Bundle",
        slug: "acc-vip-bundle",
        typeValue: "vip",
        image: "/img/ff-vip.jpg",
        priceFrom: 200000,
        stock: 22,
      },
    ],
  },
  {
    gameSlug: "lien-minh",
    gameName: "LMHT",
    gameIcon: "⚔️",
    categories: [
      {
        id: "lm-rank",
        name: "Acc Rank Cứng",
        slug: "lien-minh-acc-rank",
        typeValue: "rank",
        image: "/img/lm-rank.jpg",
        priceFrom: 100000,
        stock: 0,
      },
      {
        id: "lm-skin",
        name: "Acc Full Skin",
        slug: "lien-minh-acc-skin",
        typeValue: "skin",
        image: "/img/lm-skin.jpg",
        priceFrom: 300000,
        stock: 0,
      },
    ],
  },
  {
    gameSlug: "khac",
    gameName: "KHÁC",
    gameIcon: "🎲",
    categories: [
      {
        id: "khac-general",
        name: "Tài khoản khác",
        slug: "tai-khoan-khac",
        typeValue: "standard",
        image: "/img/other.jpg",
        priceFrom: 50000,
        stock: 0,
      },
    ],
  },
];
